# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='name_url',
            field=models.CharField(default='migrated event', max_length=5000),
            preserve_default=False,
        ),
    ]
