# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171202_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=63, primary_key=True, serialize=False, unique=True),
        ),
    ]
