# Generated by Django 2.0 on 2017-12-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20171203_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.Tag'),
        ),
    ]
