# Generated by Django 2.0 on 2017-12-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20171204_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=4000, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_url',
            field=models.CharField(max_length=4000, unique=True),
        ),
    ]
