# Generated by Django 2.0 on 2017-12-04 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20171204_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 4, 23, 52, 5, 592286, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
