# Generated by Django 2.0 on 2017-12-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_group_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='text',
            field=models.TextField(db_index=True),
        ),
    ]
