# Generated by Django 2.0 on 2017-12-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20171206_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_url',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
